version: '3'
services:
  mongodb:
    image: prismagraphql/mongo-single-replica:5.0.3
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: arduino
      MONGO_INITDB_ROOT_PASSWORD: 123
    ports:
      - 27017:27017